name: Deploy React Site

on:
  push:
    branches:
      - main # Укажите master, если ваша главная ветка называется master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20
          cache: 'npm' # или 'yarn' / 'pnpm', если используете их

      - name: Install dependencies
        run: npm ci # или npm install

      - name: Build project
        run: npm run build # Создает папку build или dist

      - name: Upload production artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # Если вы используете Vite, замените 'build' на 'dist'
          path: './build' 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
